### ISSUE TITLE
Cloud Heights error?

### ISSUE THREAD

**Issue by gonzmg88** [gee-community/geeViz#1]
Hi, 

I'm reading your code to compute cloud shadows, I've noticed that the cloudHeight list is initialized with a repeated value 500. https://github.com/gee-community/geeViz/blob/06e4e3b4cff09d43d2af525606a4d034ab257345/getImagesLib.py#L771 (also in line L2364) is this intended? Additionally, are these heights in meters? (I guess it depends on the CRS of the images used to project the shadows which would be meters in the case of Landsat and Sentinel-2 images right?)

Thank you

**Comment by rcr-usfs** [comment]
I'm just seeing this. Since this method is intended to work with Sentinel 2, which lacks thermal data, it is difficult to model the cloud height. This method therefore takes a set of possible cloud heights (in meters). The default is not a repeated list, but rather a sequence from 500 to 10000 meters every 500 meters. The function then identifies clouds, and then shifts them for each of these heights based on the solar zenith and azimuth looking for dark pixels in those areas. This method does result in false positives in dark pixels that happen to fall within any area that the clouds are projected to cover at the provided cloud heights. This does get a bit weird with geographic projections. This is not currently handled well, but is a bit here
https://github.com/gee-community/geeViz/blob/06e4e3b4cff09d43d2af525606a4d034ab257345/getImagesLib.py#L719
Hope this helps a bit.
